
version: '3.1'
# psql -U facedrive-admin fin-rec-db
# \c fin-rec-db
services:

  db:
    container_name: db.postgres.facedrive.com
    image: postgres
    tty: true
    restart: always
    environment:
      POSTGRES_USER: facedrive-admin
      POSTGRES_PASSWORD: somepass
      POSTGRES_DB: fin-rec-db
  
    ports:
    - 5432:5432

       
